#![allow(clippy::cast_possible_truncation, clippy::cast_lossless)]
//! Parity contract test — validates that Rust microGPT produces identical
//! outputs to Karpathy's Python microGPT given the same weights and inputs.
//!
//! Reference data generated by `scripts/generate_reference.py` (Python)
//! using the exact blog post forward pass with seed=42.
//!
//! Contract: `microgpt-v1.yaml` § `parity`

use aprender::autograd::{clear_graph, no_grad, Tensor};
use microgpt::*;

// ── Load reference data ─────────────────────────────────────────────────────

fn load_reference() -> serde_json::Value {
    let data = include_str!("../data/parity_reference.json");
    serde_json::from_str(data).expect("failed to parse parity_reference.json")
}

fn json_to_flat(arr: &serde_json::Value) -> Vec<f32> {
    match arr {
        serde_json::Value::Array(outer) => {
            let mut flat = Vec::new();
            for item in outer {
                match item {
                    serde_json::Value::Array(inner) => {
                        for v in inner {
                            flat.push(v.as_f64().unwrap() as f32);
                        }
                    }
                    serde_json::Value::Number(n) => {
                        flat.push(n.as_f64().unwrap() as f32);
                    }
                    _ => panic!("unexpected JSON type"),
                }
            }
            flat
        }
        _ => panic!("expected array"),
    }
}

fn json_to_tensor(arr: &serde_json::Value, shape: &[usize]) -> Tensor {
    let flat = json_to_flat(arr);
    let expected: usize = shape.iter().product();
    assert_eq!(flat.len(), expected, "shape mismatch: got {} expected {expected}", flat.len());
    Tensor::from_vec(flat, shape).requires_grad()
}

fn load_model(ref_data: &serde_json::Value) -> MicroGPT {
    let w = &ref_data["rust_weights"];

    let wte = json_to_tensor(&w["wte"], &[VOCAB_SIZE, N_EMBD]);
    let wpe = json_to_tensor(&w["wpe"], &[BLOCK_SIZE, N_EMBD]);

    let wq: Vec<Tensor> = (0..N_HEAD)
        .map(|h| json_to_tensor(&w["wq"][h], &[N_EMBD, HEAD_DIM]))
        .collect();
    let wk: Vec<Tensor> = (0..N_HEAD)
        .map(|h| json_to_tensor(&w["wk"][h], &[N_EMBD, HEAD_DIM]))
        .collect();
    let wv: Vec<Tensor> = (0..N_HEAD)
        .map(|h| json_to_tensor(&w["wv"][h], &[N_EMBD, HEAD_DIM]))
        .collect();
    let wo: Vec<Tensor> = (0..N_HEAD)
        .map(|h| json_to_tensor(&w["wo"][h], &[HEAD_DIM, N_EMBD]))
        .collect();

    let w_fc1 = json_to_tensor(&w["w_fc1"], &[N_EMBD, FF_DIM]);
    let w_fc2 = json_to_tensor(&w["w_fc2"], &[FF_DIM, N_EMBD]);
    let w_lm = json_to_tensor(&w["w_lm"], &[N_EMBD, VOCAB_SIZE]);

    MicroGPT {
        wte, wpe, wq, wk, wv, wo, w_fc1, w_fc2, w_lm,
    }
}

// ── Tokenizer parity ────────────────────────────────────────────────────────

#[test]
fn parity_tokenizer() {
    let ref_data = load_reference();
    for case in ref_data["tokenizer_cases"].as_array().unwrap() {
        let input = case["input"].as_str().unwrap();
        let expected: Vec<usize> = case["expected"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect();
        let actual = tokenize(input);
        assert_eq!(actual, expected, "tokenizer parity failed for '{input}'");
    }
}

// ── Forward pass parity ─────────────────────────────────────────────────────

#[test]
fn parity_forward_logits() {
    let ref_data = load_reference();
    let model = load_model(&ref_data);

    no_grad(|| {
        for case in ref_data["test_cases"].as_array().unwrap() {
            let name = case["name"].as_str().unwrap();
            let input_tokens: Vec<usize> = case["input_tokens"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_u64().unwrap() as usize)
                .collect();

            let rust_logits = model.forward(&input_tokens);
            let rust_data = rust_logits.data();

            let python_logits = case["logits"].as_array().unwrap();
            let n_positions = python_logits.len();

            assert_eq!(
                rust_logits.shape(),
                &[n_positions, VOCAB_SIZE],
                "shape mismatch for '{name}'"
            );

            let mut max_diff: f32 = 0.0;
            for (pos, py_logits) in python_logits.iter().enumerate() {
                let py_row: Vec<f32> = py_logits
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_f64().unwrap() as f32)
                    .collect();

                for (j, (&rust_val, &py_val)) in rust_data
                    [pos * VOCAB_SIZE..(pos + 1) * VOCAB_SIZE]
                    .iter()
                    .zip(py_row.iter())
                    .enumerate()
                {
                    let diff = (rust_val - py_val).abs();
                    if diff > max_diff {
                        max_diff = diff;
                    }
                    assert!(
                        diff < 1e-3,
                        "logit parity failed for '{name}' pos={pos} idx={j}: \
                         rust={rust_val:.6} python={py_val:.6} diff={diff:.6}"
                    );
                }
            }
            eprintln!("  parity '{name}': {n_positions} positions, max_diff={max_diff:.2e}");
        }
    });
    clear_graph();
}

// ── Loss parity ─────────────────────────────────────────────────────────────

#[test]
fn parity_loss() {
    let ref_data = load_reference();
    let model = load_model(&ref_data);

    no_grad(|| {
        for case in ref_data["test_cases"].as_array().unwrap() {
            let name = case["name"].as_str().unwrap();
            let input_tokens: Vec<usize> = case["input_tokens"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_u64().unwrap() as usize)
                .collect();

            let rust_logits = model.forward(&input_tokens);
            let rust_data = rust_logits.data();

            // Compute per-position cross-entropy loss manually
            let target_tokens: Vec<usize> = case["target_tokens"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_u64().unwrap() as usize)
                .collect();

            let py_losses: Vec<f64> = case["per_position_loss"]
                .as_array()
                .unwrap()
                .iter()
                .map(|v| v.as_f64().unwrap())
                .collect();

            for (pos, (&target, &py_loss)) in
                target_tokens.iter().zip(py_losses.iter()).enumerate()
            {
                let row = &rust_data[pos * VOCAB_SIZE..(pos + 1) * VOCAB_SIZE];
                // softmax
                let max_val = row.iter().fold(f32::NEG_INFINITY, |a, &b| a.max(b));
                let exps: Vec<f32> = row.iter().map(|&v| (v - max_val).exp()).collect();
                let sum: f32 = exps.iter().sum();
                let prob = exps[target] / sum;
                let rust_loss = -(prob.max(1e-10).ln()) as f64;

                let diff = (rust_loss - py_loss).abs();
                assert!(
                    diff < 0.05,
                    "loss parity failed for '{name}' pos={pos}: \
                     rust={rust_loss:.4} python={py_loss:.4} diff={diff:.4}"
                );
            }
            eprintln!("  loss parity '{name}': OK");
        }
    });
    clear_graph();
}

// ── Hyperparameter parity ───────────────────────────────────────────────────

#[test]
fn parity_hyperparams() {
    let ref_data = load_reference();
    let hp = &ref_data["hyperparams"];

    assert_eq!(hp["vocab_size"].as_u64().unwrap() as usize, VOCAB_SIZE);
    assert_eq!(hp["n_embd"].as_u64().unwrap() as usize, N_EMBD);
    assert_eq!(hp["n_head"].as_u64().unwrap() as usize, N_HEAD);
    assert_eq!(hp["head_dim"].as_u64().unwrap() as usize, HEAD_DIM);
    assert_eq!(hp["block_size"].as_u64().unwrap() as usize, BLOCK_SIZE);
    assert_eq!(hp["ff_dim"].as_u64().unwrap() as usize, FF_DIM);
}
